IndirectlyApp/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using IndirectlyApp.Models;

namespace IndirectlyApp.ViewModels
{
    public class HomeViewModel
    {
        public ApplicationUser CurrentUser { get; set; }
        public IEnumerable<Mosaic> Mosaics { get; set; }
    }
}

IndirectlyApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IndirectlyApp.Models;
using IndirectlyApp.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace IndirectlyApp.Controllers
{
    public class HomeController : Controller
    {
 
        private ApplicationDbContext db = new ApplicationDbContext();
        

 
        public ActionResult Index()
        {
            
            var homeViewModel = new HomeViewModel();
            var mosaics = db.Mosaics;
            var userId = User.Identity.GetUserId();

            foreach (var mosaic in mosaics)
            {
                if (mosaic.LikedBy.FirstOrDefault(x => x.Id == userId) != null)
                {
                    mosaic.IsLiked = true;
                }
            }
            homeViewModel.Mosaics = mosaics;
            var user = Request.GetOwinContext()
                .GetUserManager<ApplicationUserManager>()
                .Users.First(x => x.Id == userId);

            homeViewModel.CurrentUser = user;
            return View(homeViewModel);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

IndirectlyApp/Controllers/MosaicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using IndirectlyApp.Models;
using IndirectlyApp.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace IndirectlyApp.Controllers
{
    public class MosaicController : Controller
    {
        private static ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(db));
        // GET: Mosaic
        public ActionResult Index()
        {
            return View();
        }

        // GET: Mosaic/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Mosaic/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateComment(int mosaicId, string body)
        {

          
            try
            {
                var userId = User.Identity.GetUserId();
                var user = _userManager.FindById(userId);


                var newComment = new Comment
                {
                    User = user,
                    DateTimeCreated = DateTimeOffset.UtcNow,
                    Body = body,
                    Mosaic = db.Mosaics.Find(mosaicId)
                };

                var commentViewModel = new CommentViewModel
                {
                    Body = newComment.Body,
                    DateCreated = newComment.DateTimeCreated,
                    MosaicId = newComment.MosaicId,
                    Username = newComment.User.UserName
                };

                db.Comments.Add(newComment);


                db.SaveChanges();
                //return Json(
                //    new
                //    {
                //        Data = commentViewModel
                //    }, JsonRequestBehavior.AllowGet);
                //Response.StatusCode = (int)HttpStatusCode.OK;
                //return Json(
                //   new
                //   {
                //       Body = "fffff"
                //   }, JsonRequestBehavior.AllowGet);
                return new HttpStatusCodeResult(HttpStatusCode.OK);

            }
            catch
            {
                //Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                //return new HttpStatusCodeResult();
                return new JsonResult();
            }
        }

        // POST: Mosaic/Create
        [HttpPost]
        public ActionResult Like(int id)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                var user = _userManager.FindById(userId);
                db.Mosaics.Find(id).LikedBy.Add(user);
                db.SaveChanges();
                return new HttpStatusCodeResult(HttpStatusCode.OK);

            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
               
            }
        }
        [HttpPost]
        public ActionResult Unlike(int id)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                var user = _userManager.FindById(userId);
                db.Mosaics.Find(id).LikedBy.Remove(user);
                db.SaveChanges();
                return new HttpStatusCodeResult(HttpStatusCode.OK);

            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);

            }
        }

        // GET: Mosaic/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Mosaic/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Mosaic/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Mosaic/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

IndirectlyApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

@Scripts.Render("http://code.jquery.com/jquery-1.10.2.js")
@Scripts.Render("http://code.jquery.com/ui/1.11.4/jquery-ui.js")
@Styles.Render("http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css")
@Scripts.Render("~/Scripts/draggable.js")
@Styles.Render("~/Content/draggable.css")




<h3>Constrain movement along an axis:</h3>


<div id="wrapper" class="row col-xs-6 col-xs-offset-3" style="outline: 1px solid green; padding: 0; position: relative; min-height:1000px; ">

    <div id="item0" class="item" style="display: inline-block; position: absolute !important">
        <img id="item-img0" class="item-img" src="http://ecx.images-amazon.com/images/I/91DHR4fyOcL._UY445_.jpg" />
    </div>

    <div id="item1" class="item" style="display: inline-block; position: absolute !important">
        <img id="item-img1" class="item-img" src="http://ecx.images-amazon.com/images/I/71oNmvGHoZL._UY879_.jpg" />
    </div>

    <div id="item2" class="item" style="display: inline-block; position: absolute !important">
        <img id="item-img2" class="item-img" src="http://ecx.images-amazon.com/images/I/91DHR4fyOcL._UY445_.jpg" />
    </div>

    <div id="item3" class="item" style="display: inline-block; position: absolute !important">
        <img id="item-img3" class="item-img" src="http://ecx.images-amazon.com/images/I/71oNmvGHoZL._UY879_.jpg" />
    </div>


</div>

<div class="container">
    <br />
    <br />
    <a class="btn btn-danger col-md-12" id="click"> Coordinates </a>
</div>

IndirectlyApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IndirectlyApp/Views/Home/Index.cshtml
@model IndirectlyApp.ViewModels.HomeViewModel
@{
    ViewBag.Title = "Home Page";
}



@foreach (var mosaic in Model.Mosaics)
{
    @Html.Partial("_MosaicPartial", mosaic)
    <br/>
    @*<div class="row"></div>*@

   

}

IndirectlyApp/Views/Home/_CommentPartial.cshtml
@model IndirectlyApp.Models.Comment

IndirectlyApp/Views/Home/_MosaicPartial.cshtml
@using IndirectlyApp.Models
@model IndirectlyApp.Models.Mosaic
<div class="row">
    <div class="col-xs-6 col-xs-offset-3" style="outline: 1px solid #E5E5E5">

        <div class="row" style="background-color: #FAFAFA; padding: 8px">
            @*Username*@
            <div class="col-xs-6">@Model.User.Email</div>
            @*DatePosted*@
            <div class="col-xs-2 col-md-offset-4">4d</div>
        </div>


        <div class="row" style="margin-left: -30px !important; margin-right: -30px !important;">
            <div class="col-xs-12" style="margin-left: 0px !important; margin-right: 0px !important;"><img class="img-responsive" src="https://upload.wikimedia.org/wikipedia/commons/b/bf/Blue_Tiger_Im_IMG_9450.jpg"/>
            </div>
        </div>


        @*Likes*@

        <div class="row">
            <div class="col-xs-12">
                <strong>15 likes</strong>
            </div>
        </div>

        @*Comments*@
        <div class="row">
         
            <div class="col-xs-12" id="commentsContainer" data-mosaicid="@Model.Id">
                @foreach (var comment in Model.Comments)
                {
                    <strong>@comment.User.UserName</strong>
                    @comment.Body
                    <br/>
                }

            </div>
        </div>

        <div class="row">
            <div class="col-xs-1">
                @*@using (Html.BeginForm("Create", "Mosaic", FormMethod.Post))
            {*@

                <span id="@Model.Id" data-isliked="@Model.IsLiked.ToString()"  class="glyphicon glyphicon-heart" style="@(Model.IsLiked ? "color: red" : "color: #E5E5E5"); font-size: 1.5em; margin-top: 4px"></span>

                @*<p>
                        <input type="submit" value="Like" />
                    </p>*@
                @*}*@
            </div>
            <div class="col-xs-11 user-comment">
                <input data-mosaicid="@Model.Id" data-username="@Model.User.UserName" class="form-control input-sm user-comment" type="text">
            </div>
        </div>
        <br/>
    </div>
</div>